### PR TITLE
Split c++ into a library/plugin 

### PR DESCRIPTION
**Pull request by mariogrip**
This splits c++ and qml into separate parts, this is done to follow how
most of the components in ubuntu touch is built, it also allows other
applications to use the Matrix/uMatriks api (this idea can be expanded
on in the future). But this is mostly done due to call feature that I
have created requires this (oxide cannot handle qrc)

The way this works now, is that we now have a two "modules" one qml and
js that is not compiled/compressed this is the main "project" that
imports the libMatrix module.

This can now be started with qmlscene :)

### CODE REVIEW

**Comment by ChloeWolfieGirl** [comment]
Thank you Marius.

**Comment by delijati** [comment]
@mariogrip im unable to get it running in my branch:
```
$ qmlscene -I lib/Matrix uMatriks/Main.qml
file://xxx/uMatriks/uMatriks/Main.qml:5 module "Matrix" is not installed
```

**Comment by delijati** [comment]
Found it was error with `ChatBubble`

**Comment by delijati** [comment]
So its working now. @mariogrip in my branch in removed the need of polling for `unread` rooms.

**Pull request merged**
