### PR TITLE
Initial version of Dutch translation.

### PR DESCRIPTION
**Pull request by peter-scholtens**
All translation done for this version.

### CODE REVIEW

**Comment by Dikkeboktor** [comment]
Hi Peter, I updated the translation somewhat. Could you update the pull request with the new translations, I am not sure if and how I could do that.

**Comment by peter-scholtens** [comment]
Hello Dikkeboktor, where are the modifications you propose located?

**Comment by Dikkeboktor** [comment]
They're on uMatriks' poeditor.com page (https://poeditor.com/join/project/Og2UosRdlD)

**Comment by peter-scholtens** [comment]
Okay. Done. I assumed that strings which cannot / will not be translated should be left empty as "". Have no idea what is the preferred way, But this works too.

**Comment by Dikkeboktor** [comment]
No, I don't really know the "regular" way of doing things, but I saw the German translators had translated them. I also made some very minor improvements like aub. -> a.u.b.

**Pull request closed without merging**
